### ISSUE TITLE
Doesn't seem to do anything?

### ISSUE THREAD

**Issue by douglasg14b** [EEParker/aspnetcore-vueclimiddleware#19]
I'm trying to use this, but when running my project it doesn't seem like `vue serve` is called at all. It just runs the vanilla asp.net application with an empty window. It completely ignores the port# entered as well, nothing is served up on that port.

If I open the `vue ui` and serve from there it works as expected.

**Comment by EEParker** [comment]
Be sure you have your startup configured. 
https://github.com/EEParker/aspnetcore-vueclimiddleware#usage-example
Keep in mind, this example only works in "DEBUG" due to the compiler #if DEBUG flag.

I added some documentation for how to set up the csproj to auto-run the scripts.
https://github.com/EEParker/aspnetcore-vueclimiddleware#csproj-configuration
