### ISSUE TITLE
Timeout occurs

### ISSUE THREAD

**Issue by hnviradiya** [EEParker/aspnetcore-vueclimiddleware#7]
with all latest till date vue cli 3 and .net core 2.2
I am facing similar issue as below (below is for angular. same I am facing in vue cli).
https://github.com/aspnet/JavaScriptServices/issues/1512

**Comment by hnviradiya** [comment]
even though project was referencing .net core 2.2, internally it was using .net core 3 preview. uninstalling that resolved this issue. so closing.

**Comment by hnviradiya** [comment]
I am again having this issue. If i download this project and reference it. it is working. but if I go with nuget package. it just keeps loading and loading even after 360 seconds it is getting timed out. works with reference project. what can be reason behind this?

**Comment by EEParker** [comment]
I don't think the nuget package has been updated with the latest code.

**Comment by HeyJoel** [comment]
Hi, I'm putting together a [.NET Core Vue sample app](https://github.com/HeyJoel/Cofoundry.Samples.SPASite/tree/feature/vue) and have been running into this issue. I'd rather reference your NuGet rather than include the source code in the project, are you planning to release an updated NuGet soon?

On issue #2 you mentioned needing CI/CD, perhaps I can help with that? On Cofoundry we use a [Cake script](https://github.com/cofoundry-cms/cofoundry/blob/master/build.cake) which is run by AppVeyor and pre-release packages are deployed to MyGet. If you wanted I could put together a similar Cake script for you?

**Comment by extstopcodepls** [comment]
Is there any chance to publish newest code to nuget?

**Comment by jordanbrowneb** [comment]
I'm also having this problem intermittently. Only workaround is to restart the app several times until the problem disappears. Any update on a possible fix?

**Comment by jordanbrowneb** [comment]
Though probably a hack, this regex workaround seems to resolve the issue:

`spa.UseVueCli( "serve", regex: ".*" );`

**Comment by EEParker** [comment]
depending on the version of vue cli, you may need a different regex string than the default of "running at".
