### ISSUE TITLE
Version 3.1.2 Hot Reloading is not working. But worked with Version 3.1.1 as Project Reference

### ISSUE THREAD

**Issue by Kingside88** [EEParker/aspnetcore-vueclimiddleware#75]
Hi,

thank you for your're last NuGet Update 3.1.2 where the options for wsl and https are available now.
But now Hot reoloading is not working.
I tried my sample project with NuGet 3.1.2 and 3.1.1 as Project reference.
 
And why do you removed the "mkcert" part from Readme.md here in GitHub?

Here is my startup.cs:
`                endpoints.MapToVueCliProxy(
                    pattern: "en/{*path}", 
                    options: new SpaOptions { SourcePath = "ClientApp" },
                    npmScript: (System.Diagnostics.Debugger.IsAttached) ? "serve" : null,
                    port: 8080,
                    https: true,
                    runner: ScriptRunnerType.Npm,
                    regex: "Compiled successfully",
                    forceKill: true
                    //wsl: false
                    );`
And here my vue.config.cs
`const fs = require('fs')

module.exports = {
	publicPath: '/en/',
    devServer: {
        https: {
            key: fs.readFileSync('../certs/localhost+3-key.pem'),
            cert: fs.readFileSync('../certs/localhost+3.pem'),
        }
    }	
};`

**Comment by TobbenTM** [comment]
I made the change to remove the mkcert part of the README because I think it shouldn't be part of the default experience. With the last version of this library, you don't need to run the Vue CLI server over HTTPS in order for HMR to work when the ASP.Net backend is running on HTTPS.

You should be able to simplify your sample project by removing the Vue config and `https` options from the MapToVueCliProxy. 

Of course, if you know what you're doing, you can still run the Vue CLI over HTTPS, but then you need to specify the public devServer option as expected:

```
module.exports = {
    devServer: {
        public: '<your vue url>'
    }
};
```
